version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./apps/backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    env_file:
      - .env

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
